### ISSUE TITLE
Can not reproduce the training reward with stable baseline3

### ISSUE THREAD

**Issue by chenxi-yang** [PCCproject/PCC-RL#19]
Hi,

I can not use the setting with stablebaselines because of the TensorFlow version issue. I tried to use the PPO in stable-baseline3 instead. However, both the reward and ewma reward are super unstable and can not reach the 7000 reported in the paper. May I ask if the print(reward..., ewma...) in the reset() function is the reported reward in the paper? If yes, which one is the training reward reported (reward or ewma reward)? 

As a side point, did you find the learning performance sensitive to the parameters of PPO(e.g. timesteps_per_actorbatch, schedule, etc.)? The new version of PPO in stable-baseline3 does not have these parameters. So it's hard to 100% copy the training process as in this repo.

Thank you very much!
Bests,

**Comment by chenxi-yang** [comment]
Hi as a complement, I tried the tf1 version of PCC-RL, which is the same as the default setting in this repo. However, the training reward I can get is ~ 1000 (However, in the paper, the reported training reward is around 6000), could you help me figure this out?

**Comment by r02b** [comment]
Hi ChenXi,

It was great talking to you the other day.

I reviewed the logs you sent me, and talked to a few other team members who have been using this repo to reproduce our work. It seems that due to some changes in TF2, you cannot automatically use the newer version (there is a team member who was able to use the newer version, but it did required a few minor modifications to the code). Similar issues have also appeared in the new stable-baselines3 version (which was obviously not out when we published), but I'm afraid I don't have more information on how to upgrade to that version.

As you mentioned during our talk that you have upgraded some of the TF1.5 methods to TF2, and from looking at the logs you sent me, I suspect that's the problem you've been experiencing. 

I suggest using TF1.5 to start with (not upgrading anything), it should be working ootb, meaning you should see the learning converging, and the resulting agent yielding the same results shown in the paper.


Best,
Noga

**Comment by r02b** [comment]
Partial requirements file for posterity:

tensorflow==1.15
tensorboard==1.15
stable-baselines==2.10.1
gym==0.18.0

**Comment by chenxi-yang** [comment]
Hi Noga,

 I tried the requirements as above, and no change to the code except for the total_timesteps in the model.learn(). The original total_timesteps supports 80 iterations and I changed it to 10000*8192.

But the training still does not converge. 

Bests,
Chenxi

**Comment by jessewjx** [comment]
Hi Chenxi,

I am currently reproducing the result as well but encountered a similar issue here, I am wondering if you have any insights or suggestions on this? 
Thank you very much!

I am using the requirement as above as well and I have an 
"ImportError: cannot import name 'PPO1' from 'stable_baselines'"

`/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
WARNING: Logging before flag parsing goes to stderr.
W0409 19:45:32.320918 4432778752 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "stable_solve.py", line 21, in <module>
    from stable_baselines import PPO1
ImportError: cannot import name 'PPO1' from 'stable_baselines' (/usr/local/lib/python3.7/site-packages/stable_baselines/__init__.py)`

Best,
Juexiao

**Comment by chenxi-yang** [comment]
Hi Juexiao,

For the error you posted, downgrading the stable baseline version to 2.10 and TensorFlow to 1.15 might help.

**Comment by jessewjx** [comment]
Hi Chenxi,

Thank you very much for your kind reply and I just tried with these versions but still having the same issue...

Best,
Juexiao

**Comment by chenxi-yang** [comment]
Hi Juexiao,

Here is a list of requirements I got from the authors. The second column is the version they use. Hope it could help.



Jinja2 | 2.11.3 | 3.1.2
-- | -- | --
Keras-Applications | 1.0.8 | 1.0.8
Keras-Preprocessing | 1.1.2 | 1.1.2
Markdown | 3.3.3 | 3.3.7
MarkupSafe | 1.1.1 | 2.1.1
Pillow | 7.2.0 | 9.1.1
Pygments | 2.8.0 | 2.12.0
QtPy | 1.9.0 | 2.1.0
Send2Trash | 1.5.0 | 1.8.0
Theano | 1.0.5 | 1.0.5
Werkzeug | 1.0.1 | 2.1.2
absl-py | 0.11.0 | 1.0.0
argon2-cffi | 20.1.0 | 21.3.0
astor | 0.8.1 | 0.8.1
async-generator | 1.10 |  
atari-py | 0.2.6 | 0.3.0
attrs | 20.3.0 | 21.4.0
backcall | 0.2.0 | 0.2.0
batchOpenMPI | 0.2.2 | 0.2.2
bleach | 3.3.0 | 5.0.0
cached-property | 1.5.2 | 1.5.2
cffi | 1.14.5 | 1.15.0
cloudpickle | 1.6.0 | 2.1.0
coloredlogs | 15.0 | 15.0.1
cycler | 0.10.0 | 0.11.0
decorator | 4.4.2 | 5.1.1
defusedxml | 0.6.0 | 0.7.1
entrypoints | 0.3 | 0.4
future | 0.18.2 | 0.18.2
gast | 0.4.0 | 0.5.3
google-pasta | 0.2.0 | 0.2.0
grpcio | 1.35.0 | 1.46.3
gym | 0.18.0 | 0.24.0
h5py | 3.1.0 | 3.7.0
humanfriendly | 9.1 | 10.0
importlib-metadata | 3.4.0 | 4.11.4
ipykernel | 5.4.3 | 6.13.0
ipython | 7.20.0 | 8.4.0
ipython-genutils | 0.2.0 |  
ipywidgets | 7.6.3 | 7.7.0
jedi | 0.18.0 | 0.18.1
joblib | 1.0.1 | 1.1.0
jsonschema | 3.2.0 | 4.5.1
jupyter-client | 6.1.11 | 7.3.1
jupyter-console | 6.2.0 | 6.4.3
jupyter-core | 4.7.1 | 4.10.0
jupyterlab-pygments | 0.1.2 | 0.2.2
jupyterlab-widgets | 1.0.0 | 1.1.0
kiwisolver | 1.3.1 | 1.4.2
matplotlib | 3.3.4 | 3.5.2
mistune | 0.8.4 | 2.0.2
mpi4py | 3.0.3 | 3.1.3
nbclient | 0.5.2 | 0.6.3
nbconvert | 6.0.7 | 6.5.0
nbformat | 5.1.2 | 5.4.0
nest-asyncio | 1.5.1 | 1.5.5
notebook | 6.2.0 | 6.4.11
numpy | 1.20.1 | 1.22.4
onnx | 1.8.1 | 1.11.0
onnxruntime | 1.6.0 | 1.11.1
onnxruntime-tools | 1.6.0 | 1.7.0
opencv-python | 4.5.1.48 | 4.5.5.64
packaging | 20.9 | 21.3
pandas | 1.2.2 | 1.4.2
pandocfilters | 1.4.3 | 1.5.0
parso | 0.8.1 | 0.8.3
pexpect | 4.8.0 | 4.8.0
pickleshare | 0.7.5 | 0.7.5
pip | 21.0.1 | 22.1.2
prometheus-client | 0.9.0 | 0.14.1
prompt-toolkit | 3.0.16 | 3.0.29
protobuf | 3.14.0 | 4.21.1
psutil | 5.8.0 | 5.9.1
ptyprocess | 0.7.0 | 0.7.0
py-cpuinfo | 7.0.0 | 8.0.0
py3nvml | 0.2.6 | 0.2.7
pycparser | 2.20 | 2.21
pyglet | 1.5.0 | 1.5.26
pyparsing | 2.4.7 | 3.0.9
pyrsistent | 0.17.3 | 0.18.1
python-dateutil | 2.8.1 | 2.8.2
pytz | 2021.1 | 2022.1
pyzmq | 22.0.3 | 23.0.0
qtconsole | 5.0.2 | 5.3.0
scipy | 1.6.0 | 1.8.1
seaborn | 0.11.1 | 0.11.2
setuptools | 53.0.0 | 62.3.2
six | 1.15.0 | 1.16.0
stable-baselines | 2.10.1 | 2.10.2
tensorboard | 1.14.0 | 2.9.0
tensorflow | 1.14.0 | 2.9.1
tensorflow-estimator | 1.14.0 | 2.9.0
termcolor | 1.1.0 | 1.1.0
terminado | 0.9.2 | 0.15.0
testpath | 0.4.4 | 0.6.0
tornado | 6.1 | 6.1
traitlets | 5.0.5 | 5.2.1.post0
typing-extensions | 3.7.4.3 | 4.2.0
wcwidth | 0.2.5 | 0.2.5
webencodings | 0.5.1 | 0.5.1
wheel | 0.36.2 | 0.37.1
widgetsnbextension | 3.5.1 | 3.6.0
wrapt | 1.12.1 | 1.14.1
xmltodict | 0.12.0 | 0.13.0
zipp | 3.4.0 | 3.8.0

**Comment by jessewjx** [comment]
Hi Chenxi,

Thank you so much and I would have a try!

Best regards,
Juexiao

**Comment by aniket25rl** [comment]
Hi @chenxi-yang , @jessewjx,

Were you able to replicate the results?
